### ISSUE TITLE
USER STORY: <Feedback Comments>

### ISSUE THREAD

**Issue by beratzorlu** [beratzorlu/primis-repo#5]
As a **user** I can **write and publish personal comments** so that **I can share feedback relevant to my experience without being limited to options in a poll**.

**Acceptance Criteria**:
- The user should be notified once their submission is pushed successfully to the server.
- The user should be able to interact with a text editor while creating their comment.
- An error message should display if the user provides invalid text (profanity, excessive text duplication, etc.) before their submission.

**Tasks**:
 - [x] Take the user to a separate webpage that informs them of the success of their submission attempt.
 - [ ] Send the user an automated email that informs that of the success of their submission attempt 
 - [ ] Implement disqus.com functionality for an integrated text editor.
 - [x] Display a pop-up if the user provides invalid text content.

**Comment by beratzorlu** [comment]
**Acceptance Criteria**:

- Use JQuery, PHP and Ajax for developing the comment section.
- User JavaScript to connect to the Push Library for real-time connectivity.
